apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: my-api

  name: my-api-hpa-nrpz
  namespace: default
spec:
  maxReplicas: 7
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 90
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-api