apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-api
  name: my-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - image: gcr.io/nimble-charmer-336120/my-api-project
        imagePullPolicy: Always 
        name: my-api-project-sha256-1
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: database
      - name: cloud-sql-proxy
          # It is recommended to use the latest version of the Cloud SQL proxy
          # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
            - "/cloud_sql_proxy"

            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            # - "-ip_address_types=PRIVATE"

            # Replace DB_PORT with the port the proxy should listen on
            # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
            - "-instances=nimble-charmer-336120:us-central1:mypostgresql=tcp:5432"

          # [START cloud_sql_proxy_k8s_volume_mount]
            # This flag specifies where the service account key can be found
            - "-credential_file=/secrets/service_account.json"
        securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        volumeMounts:
        - name: mydbsa-secret
          mountPath: /secrets/
          readOnly: true
            # [END cloud_sql_proxy_k8s_volume_mount]
          # Resource configuration depends on an application's requirements. You
          # should adjust the following values based on what your application
          # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          requests:
              # The proxy's memory use scales linearly with the number of active
              # connections. Fewer open connections will use less memory. Adjust
              # this value based on your application's requirements.
            memory: "2Gi"
              # The proxy's CPU use scales linearly with the amount of IO between
              # the database and the application. Adjust this value based on your
              # application's requirements.
            cpu:    "1"
        # [START cloud_sql_proxy_k8s_volume_secret]
    volumes:
    - name: mydbsa-secret
      secret:
        secretName: mydbsa-secret
        # [END cloud_sql_proxy_k8s_volume_secret]
